### ISSUE TITLE
bundlewatch is broken with brotli-size 3

### ISSUE THREAD

**Issue by gex** [bundlewatch/bundlewatch#60]
i get this output with `brotli-size` `3.0.1`:

```
yarn run v1.17.3
$ bundlewatch --config bundlewatch.config.json
TypeError: brotli.sync is not a function
    at getBrotliSize (/app/node_modules/bundlewatch/lib/app/getLocalFileDetails/getSize.js:32:19)
    at getSize (/app/node_modules/bundlewatch/lib/app/getLocalFileDetails/getSize.js:50:20)
    at paths.forEach.filePath (/app/node_modules/bundlewatch/lib/app/getLocalFileDetails/index.js:40:52)
    at Array.forEach (<anonymous>)
    at files.forEach.file (/app/node_modules/bundlewatch/lib/app/getLocalFileDetails/index.js:37:19)
    at Array.forEach (<anonymous>)
    at getLocalFileDetails (/app/node_modules/bundlewatch/lib/app/getLocalFileDetails/index.js:28:11)
    at /app/node_modules/bundlewatch/lib/app/index.js:47:76
    at Generator.next (<anonymous>)
    at step (/app/node_modules/bundlewatch/lib/app/index.js:38:191)
[FATAL] Uncaught exception
error Command failed with exit code 1.
```

i had to set the version to `1.0.0` to run it successfully.

environment:
- node `10.16.0`
- yarn `1.17.3`
- bundlewatch `0.2.5`
- brotli-size `3.0.1`

**Comment by iamogbz** [comment]
Looks like an issue introduced in `brotli-size@^3.0.0` fixed in `v4.0.0`

`yarn add brotli-size@^3.0.0`
```sh
> require('brotli-size').sync
undefined
```
`yarn add brotli-size@^4.0.0`
```sh
> require('brotli-size').sync
[Function: sync]
```
